apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spr-app
  template:
    metadata:
      labels:
        app: spr-app
    spec:
      containers:
        - name: spr-app
          image: subramanya777-spr-image:v1
          ports:
            - containerPort: 8081
          env:
            - name: ENV_VARIABLE_1
              value: "value1"
            - name: ENV_VARIABLE_2
              value: "value2"

